apiVersion: v1
data:
  deployment.toml: |
    [server]
    hostname = "apim.local"
    node_ip = "$env{NODE_IP}"
    offset = 0
    mode = "single" #single or ha
    base_path = "${carbon.protocol}://${carbon.host}:${carbon.management.port}"
    #discard_empty_caches = false
    server_role = "default"
    
    [user_store]
    type = "database_unique_id"
    
    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true
    
    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://mysql.wso2.svc.cluster.local:3306/WSO2AM_DB?useSSL=false&amp;allowPublicKeyRetrieval=true"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    
    [database.apim_db.pool_options]
    defaultAutoCommit = "true"
    maxActive = "50"
    maxWait = "60000"
    minIdle = "5"
    testOnBorrow = "true"
    testWhileIdle = "true"
    validationInterval = "30000"
    
    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://mysql.wso2.svc.cluster.local:3306/WSO2AM_SHARED_DB?useSSL=false&amp;allowPublicKeyRetrieval=true"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    
    [database.shared_db.pool_options]
    defaultAutoCommit = "true"
    maxActive = "50"
    maxWait = "60000"
    minIdle = "5"
    testOnBorrow = "true"
    testWhileIdle = "true"
    validationInterval = "30000"
    
    [apim]
    gateway_type = "Regular,APK,AWS,Azure,Kong"
    [keystore.tls]
    type = "JKS"
    file_name = "wso2carbon.jks"
    alias = "wso2carbon"
    password = "wso2carbon"
    key_password = "wso2carbon"
    
    [truststore]
    type = "JKS"
    file_name = "client-truststore.jks"
    password = "wso2carbon"
    [[apim.gateway.environment]]
    name = "Default"
    type = "hybrid"
    gateway_type = "Regular"
    provider = "wso2"
    display_in_api_console = true
    description = "This is a hybrid gateway that handles both production and sandbox token traffic."
    show_as_token_endpoint_url = true
    service_url = "https://apim-gw-wso2am-gateway-service:9443/services/"
    username= "${admin.username}"
    password= "${admin.password}"
    ws_endpoint = "ws://websocket.local"
    wss_endpoint = "wss://websocket.local"
    http_endpoint = "http://gw.local"
    https_endpoint = "https://gw.local"
    websub_event_receiver_http_endpoint = "http://websub.local"
    websub_event_receiver_https_endpoint = "https://websub.local"
    
    [apim.sync_runtime_artifacts.gateway]
    gateway_labels = ["Default"]
    
    # Caches
    [apim.cache.gateway_token]
    enable = true
    expiry_time = "15m"
    
    [apim.cache.resource]
    enable = true
    expiry_time = "900s"
    
    [apim.cache.km_token]
    enable = true
    expiry_time = "15m"
    
    [apim.cache.recent_apis]
    enable = false
    
    [apim.cache.scopes]
    enable = false
    
    [apim.cache.publisher_roles]
    enable = false
    
    [apim.cache.jwt_claim]
    enable = true
    expiry_time = "15m"
    
    [apim.cache.tags]
    enable = true
    expiry_time = "2m"
    
    [apim.analytics]
    enable = false
    
    [apim.ai]
    enable = false
    [apim.mcp]
    enable = true
    
    [transport.http]
    properties.port = 9763
    properties.proxyPort = 80
    
    [transport.https]
    properties.port = 9443
    properties.proxyPort = 443
    
    # key manager implementation
    [apim.key_manager]
    service_url = "https://apim-wso2am-all-in-one-am-service:${mgt.transport.https.port}/services/"
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"
    enable_lightweight_apikey_generation = true
    allow_subscription_validation_disabling = true
    skip_create_resident_key_manager = false
    
    [apim.transaction_counter]
    enable = false
    server_id = "Gateway"
    
    [oauth.grant_type.token_exchange]
    enable = true
    allow_refresh_tokens = true
    iat_validity_period = "1h"
    
    [oauth.endpoints]
    oauth2_jwks_url = "https://apim-wso2am-all-in-one-am-service:9443/oauth2/jwks"
    
    #[apim.idp]
    #server_url = "https://localhost:${mgt.transport.https.port}"
    #authorize_endpoint = "https://localhost:${mgt.transport.https.port}/oauth2/authorize"
    #oidc_logout_endpoint = "https://localhost:${mgt.transport.https.port}/oidc/logout"
    #oidc_check_session_endpoint = "https://localhost:${mgt.transport.https.port}/oidc/checksession"
    
    # JWT Generation
    
    [apim.oauth_config]
    remove_outbound_auth_header = true
    auth_header = "Authorization"
    revoke_endpoint = ""
    enable_token_encryption = false
    enable_token_hashing = false
    
    [apim.devportal]
    url = "https://apim.local/devportal"
    mode = "HYBRID"
    
    [apim.publisher]
    enable_api_doc_visibility = false
    
    [apim.cors]
    enable = true
    allow_origins = ["*"]
    allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
    allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey","Internal-Key"]
    allow_credentials = false
    enable_validation_for_ws = false
    # Traffic Manager configurations
    [apim.throttling]
    event_duplicate_url = ["tcp://apim-wso2am-all-in-one-am-service-1:5672"]
    throttle_decision_endpoints = ["tcp://localhost:5672"]
    
    [apim.throttling.blacklist_condition]
    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://apim-wso2am-all-in-one-am-service-1:9611"]
    traffic_manager_auth_urls = ["ssl://apim-wso2am-all-in-one-am-service-1:9711"]
    type = "loadbalance"
    
    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://apim-wso2am-all-in-one-am-service-2:9611"]
    traffic_manager_auth_urls = ["ssl://apim-wso2am-all-in-one-am-service-2:9711"]
    type = "loadbalance"
    
    
    # [[apim.throttling.url_group]]
    # traffic_manager_urls = ["tcp://apim-wso2am-all-in-one-am-service:9611"]
    # traffic_manager_auth_urls = ["ssl://apim-wso2am-all-in-one-am-service:9711"]
    # type = "failover"
    
    # Data Bridge Configuration
    # [transport.receiver]
    # type =
    # worker_threads = 10
    # session_timeout = ""
    # keystore.file_name = "$ref{keystore.tls.file_name}"
    # keystore.password = "$ref{keystore.tls.password}"
    # tcp_port = 9611
    # ssl_port = 9711
    # ssl_receiver_thread_pool_size = 100
    # tcp_receiver_thread_pool_size = 100
    # ssl_enabled_protocols = [TLSv1","TLSv1.1","TLSv1.2]
    # ciphers = [SSL_RSA_WITH_RC4_128_MD5","SSL_RSA_WITH_RC4_128_SHA]
    
    # [apim.token.revocation]
    # notifier_impl = "org.wso2.carbon.apimgt.keymgt.events.TokenRevocationNotifierImpl"
    # enable_realtime_notifier = true
    # realtime_notifier_ttl = 5000
    # enable_persistent_notifier = true
    # persistent_notifier_hostname = "https://localhost:2379/v2/keys/jti/"
    # persistent_notifier_ttl = 5000
    # persistent_notifier_username = "root"
    # persistent_notifier_password = "root"
    [[event_handler]]
    name = "userPostSelfRegistration"
    subscriptions = ["POST_ADD_USER", ]
    
    [service_provider]
    sp_name_regex = "^[\\sa-zA-Z0-9._-]*$"
    
    [[event_listener]]
    id = "token_revocation"
    type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
    name = "org.wso2.is.notification.ApimOauthEventInterceptor"
    order = 1
    
    [event_listener.properties]
    notification_endpoint = "https://apim-wso2am-all-in-one-am-service:${mgt.transport.https.port}/internal/data/v1/notify"
    username = "${admin.username}"
    password = "${admin.password}"
    'header.X-WSO2-KEY-MANAGER' = "default"
    [database.local]
    url = "jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"
    [apim.sdk]
    supported_languages = ["android","java","csharp","dart","groovy","javascript","jmeter","perl","php","python","ruby","swift5","clojure"]
    
    [apim.organization_based_access_control]
    enable = true
    organization_name_local_claim = "http://wso2.org/claims/organization"
    organization_id_local_claim = "http://wso2.org/claims/organizationId"
    
    [apim.gateway_notification]
    enabled = true
    gateway_id = ""
    
    [apim.gateway_notification.heartbeat]
    notify_interval = "1m"
    
    [apim.gateway_notification.deployment_ack]
    batch_size = 100
    batch_interval = "2s"
    max_retry_count = 5
    retry_duration = "10s"
    retry_progression_factor = 2
    batch_processor_min_thread = 2
    batch_processor_max_thread = 8
    batch_processor_keep_alive = "1m"
    batch_processor_queue_size = 50
    
    [apim.gateway_notification.registration]
    max_retry_count = 5
    retry_duration = "10s"
    retry_progression_factor = 2
    
    [apim.gateway_notification.cleanup]
    expiry_time = "2m"
    data_retention_period = "30d"
kind: ConfigMap
metadata:
  name: apim-wso2am-all-in-one-am-conf-2
  namespace: wso2
