---
- name: Deploy WSO2 APIM Stack
  hosts: localhost
  connection: local
  vars:
    git_repo_url: "https://github.com/didee97/apim-kube.git"
    git_branch: "main"
    base_path: "/tmp/apim_deployment"
    target_namespace: "wso2"
    istio_version: "1.26.1"

  vars_prompt:
    - name: install_istio
      prompt: "Do you want to install Istio? (yes/no)"
      private: no
    - name: apim_domain
      prompt: "Enter APIM domain"
      default: "apim.local"
      private: no
    - name: gw_domain
      prompt: "Enter Gateway domain"
      default: "gw.local"
      private: no

  tasks:
    - name: 1. Clone Manifests from Git
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ base_path }}"
        version: "{{ git_branch }}"
        force: yes

    - name: 2. Ensure wso2 Namespace Exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ target_namespace }}"
        state: present

    - name: 3. Check Istio Installation Status
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: istio-system
      register: istio_check
      ignore_errors: yes

    - name: Debug Istio Check
      debug:
        var: istio_check

    - name: 4. Install Istio & Label Namespace
      block:
        - name: Download and Install Istio
          shell: |
            curl -L https://istio.io/downloadIstio | ISTIO_VERSION={{ istio_version }} sh -
            ./istio-{{ istio_version }}/bin/istioctl install --set profile=demo -y
          args:
            chdir: "{{ base_path }}"
      when: 
        - install_istio | bool
        - istio_check.resources | length == 0

    - name: Enable Sidecar Injection for wso2
      command: "kubectl label namespace {{ target_namespace }} istio-injection=enabled --overwrite"
      when: istio_check.resources | length != 0

    - name: 5. Handle Certificates & Domain Logic
      block:
        - name: Run certificate generation script
          shell: "./scripts/generate-local-certificates.sh {{ apim_domain }} {{ gw_domain }}"
          args:
            chdir: "{{ base_path }}"

        - name: Create Istio Ingress Secret
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: wso2-ingress-cert
                namespace: istio-system
              type: kubernetes.io/tls
              data:
                # This reads the files generated by your script and encodes them to base64
                tls.crt: "{{ lookup('file', base_path + '/certificates/server.crt') | b64encode }}"
                tls.key: "{{ lookup('file', base_path + '/certificates/server.key') | b64encode }}"

        - name: Update APIM and Gateway Domains in all manifests
          replace:
            path: "{{ base_path }}/{{ item.0 }}"
            regexp: "{{ item.1.pattern }}"
            replace: "{{ item.1.replacement }}"
          with_nested:
            - [ 'istio-gateway.yaml', 'cm-cp1.yaml', 'cm-cp2.yaml', 'cm-gw.yaml' ]
            - - { pattern: 'apim\.local', replacement: "{{ apim_domain }}" }
              - { pattern: 'gw\.local',   replacement: "{{ gw_domain }}" }

        - name: Apply Istio Gateway and VirtualService
          kubernetes.core.k8s:
            state: present
            namespace: "{{ target_namespace }}"
            src: "{{ base_path }}/istio-gateway.yaml"
      when: istio_check.resources | length != 0

    - name: 6. Deploy MySQL Database
      block:
        - name: Run MySQL Setup Script
          shell: "./scripts/deploy-mysql.sh"
          args:
            chdir: "{{ base_path }}"
        
    - name: 7. Deploy WSO2 CP
      kubernetes.core.k8s:
        state: present
        namespace: "{{ target_namespace }}"
        src: "{{ base_path }}/{{ item }}"
      loop:
        - cm-cp1.yaml
        - cm-cp2.yaml
        - service-cp.yaml
        - deployment-cp1.yaml
        - deployment-cp2.yaml

    - name: 8. Deploy WSO2 GW
      kubernetes.core.k8s:
        state: present
        namespace: "{{ target_namespace }}"
        src: "{{ base_path }}/{{ item }}"
      loop:
        - cm-gw.yaml
        - service-gw.yaml
        - deployment-gw.yaml

    - name: 9. Verify Deployment
      debug:
        msg: "Successfully deployed to {{ target_namespace }}. Istio status: {{ 'Installed' if install_istio|bool else 'Skipped' }}"
